# Generated by Django 3.2.4 on 2021-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phonenumber', models.TextField(verbose_name='phone_number')),
                ('productname', models.TextField(verbose_name='productname')),
                ('quantity', models.TextField(default='1', verbose_name='quantity')),
            ],
        ),
    ]
