# Generated by Django 3.2.4 on 2021-08-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(verbose_name='User name')),
                ('product_name', models.TextField(max_length=255, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Date ordered')),
                ('date_required', models.DateField(verbose_name='Date required')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
